workspace:
  base: /go
  path: src/github.com/metalmatze/alertmanager-bot

pipeline:
  build:
    image: golang:alpine
    commands:
      - apk add -U git make
      - make fmt
      - make vet
      - make lint
      - make test
      - make build

  docker:
    image: plugins/docker
    repo: metalmatze/alertmanager-bot
    tags: ['latest']
    when:
      event: [ push ]
      branch: [ master ]
