workspace:
  base: /go
  path: src/github.com/metalmatze/alertmanager-bot

pipeline:
  dep:
    image: metalmatze/dep:0.4.1
    commands:
      - dep ensure -v -vendor-only

  build:
    image: golang:1.10-alpine
    pull: true
    commands:
      - apk add -U git make
      - make fmt
      - make vet
      - make lint
      - make test
      - make build
    when:
      event: [ push, tag, pull_request ]

  release:
    image: golang:1.10-alpine
    commands:
      - apk add -U git make
      - make release
    when:
      event: tag

  docker:
    image: plugins/docker
    repo: metalmatze/alertmanager-bot
    secrets: [ docker_username, docker_password ]
    tag: [ 0.3, 0.3.0 ]
    when:
      event: tag

  github:
    image: plugins/github-release
    secrets: [ github_token ]
    files: dist/*
    when:
      event: tag
